<?php
// Theme localization Fields
if( !function_exists('propertya_localization') )
{
    function propertya_localization()
	{
		global $localization;
		//global $propertya_options;
        $localization = array
	    (
		    'keyword' => esc_html__('Keyword','propertya'),
	   		'property_type' => esc_html__('Property Type','propertya'),
			'property_stat' => esc_html__('Property Status','propertya'),
			'offer_type' 	=> esc_html__('Offer Type','propertya'),
			'property_label' => esc_html__('Label','propertya'),
			'currecny_type' => esc_html__('Currency Type','propertya'),
			'property_price' => esc_html__('Property Price','propertya'),
			'snd_price' 	=> esc_html__('Second Price (Optional)','propertya'),
			'before_price' => esc_html__('Before Price Label','propertya'),
			'after_price' => esc_html__('After Price Label','propertya'),
			'property_area' => esc_html__('Area Size','propertya'),
			'area_prefix' => esc_html__('Area Size Prefix ','propertya'),
			'land_area' => esc_html__('Land Area','propertya'),
			'land_area_prefix' => esc_html__('Land Area Prefix','propertya'),
			'bedrooms' => esc_html__('Bedrooms','propertya'),
            'full_rooms' => esc_html__('Bedrooms','propertya'),
			'bathrooms' => esc_html__('Bathrooms','propertya'),
			'grages' => esc_html__('Garages','propertya'),
			'yearbuild' => esc_html__('Year Built','propertya'),
			'amenities' => esc_html__('Amenities and Features','propertya'),
			'video' => esc_html__('Video URL','propertya'),
			'virtual_tour' => esc_html__('360 Virtual Tour Iframe','propertya'),
			'desc' => esc_html__('Description Box','propertya'),
			'gallery' => esc_html__('Gallery','propertya'),
			'zip_code' => esc_html__('Zipcode','propertya'),
			'street_location' => esc_html__('Street Address','propertya'),
			'map' => esc_html__('Map','propertya'),
			'coordinates' => esc_html__('Coordinates','propertya'),
			'location' => esc_html__('Location (Country / State / Town)','propertya'),
			'floorplan' => esc_html__('Floor Plans','propertya'),
			'additional_fields' => esc_html__('Additional Fields','propertya'),
			'attachments' => esc_html__('Attachments','propertya'),
			'dashboard' => esc_html__('Dashboard','propertya'),
			'profile' => esc_html__('My Profile','propertya'),
			'my_properties' => esc_html__('My Properties','propertya'),
			'ad_property' => esc_html__('Add New Property','propertya'),
			'pub' => esc_html__('Published','propertya'),
			'pend' => esc_html__('Pending','propertya'),
			'feat' => esc_html__('Featured','propertya'),
			'exp' => esc_html__('Expired','propertya'),
			'a_listing' => esc_html__('Search listing','propertya'),
			'action' => esc_html__('Action','propertya'),
			'price' => esc_html__('Price','propertya'),
			'listed_in' => esc_html__('Listed In','propertya'),
			'listing' => esc_html__('Listing','propertya'),
			'publish' => esc_html__('Published Properties','propertya'),
			'expired' => esc_html__('Expired Properties','propertya'),
			'pending' => esc_html__('Pending Properties','propertya'),
			'featured' => esc_html__('Featured Properties','propertya'),
			'approval' => esc_html__(' Approval Required!','propertya'),
			'approval_notify' => esc_html__('Waiting for admin approval. ','propertya'),
			'agents' => esc_html__('Agents','propertya'),
			'agent_name' => esc_html__('Agent Name','propertya'),
			'display_name' => esc_html__('Display Name','propertya'),
			'add_new_agent' => esc_html__('Add New Agent','propertya'),
			'edit_new_agent' => esc_html__('Edit Agent Listing','propertya'),
			'view_all_agent' => esc_html__('View All Agent','propertya'),
			'edit_agent_list'=> esc_html__('Edit Agent Listing','propertya'),
			'username' => esc_html__('Username','propertya'),
			'email' => esc_html__('Email','propertya'),
			'agent_type' => esc_html__('Agent Type','propertya'),
			'agent_type_req' => esc_html__('Agent type is required.','propertya'),
			'contact_num' => esc_html__('Mobile Number','propertya'),
			'pass' => esc_html__('Password','propertya'),
			'agent-listings' => esc_html__('Agent Listing','propertya'),
			'agent_req'=> esc_html__('Assign listing to Agent','propertya'),
			'u_required' => esc_html__('Username is required.','propertya'),
			'email_required' => esc_html__('You have not given a correct e-mail address.','propertya'),
			'pass_required' => esc_html__('Please choose a password with at least 3-12 characters.','propertya'),
			'snd_email' => esc_html__('Send the new user an email about their account.','propertya'),
			'search_agents' => esc_html__('Search agents...','propertya'),
			'my_agents' => esc_html__('Agents','propertya'),
			'agency_name' => esc_html__('Agency Name','propertya'),
			'my_expiry' => esc_html__('Expire On','propertya'),
			'my_mob' => esc_html__('Mobile Number','propertya'),
			'my_whatsapp' => esc_html__('WhatsApp Number','propertya'),
			'my_office' => esc_html__('Office Number','propertya'),
			'my_fax' => esc_html__('Fax Number','propertya'),
			'my_agency_lic' => esc_html__('License Number','propertya'),
			'my_licence' => esc_html__('Agency License','propertya'),
			'my_taxno' => esc_html__('Tax Number','propertya'),
			'my_weburl' => esc_html__('Website Url','propertya'),
			'my_agency_loc' => esc_html__('Agency Location','propertya'),
			'my_about_agency' => esc_html__('About Agency','propertya'),
			'my_about_agent' => esc_html__('About Agent','propertya'),
			'my_about_yourself' => esc_html__('About Yourself','propertya'),
			'buyer_loc' => esc_html__('Your Location','propertya'),
			'my_fb' => esc_html__('Facebook URL','propertya'),
			'my_tw' => esc_html__('Twitter URL','propertya'),
			'my_ln' => esc_html__('LinkedIn URL','propertya'),
			'my_insta' => esc_html__('Instagram URL','propertya'),
			'my_you' => esc_html__('Youtube URL','propertya'),
			'my_pint' => esc_html__('Pinterest URL','propertya'),
			'my_addr' => esc_html__('Address','propertya'),
			'my_coord' => esc_html__('Coordinates','propertya'),
			'save_changes' => esc_html__('Save Changes','propertya'),
			'agency_loc' => esc_html__('Agency Location','propertya'),
			'agent_loc' => esc_html__('Agent Location','propertya'),
			'social_media' => esc_html__('Social Media','propertya'),
			'account_settings' => esc_html__('Account Settings','propertya'),
			'my_profile' => esc_html__('My Profile','propertya'),
			'feat_img' => esc_html__('Featured Image','propertya'),
			'edit_pass' => esc_html__('Edit Password','propertya'),
			'current_pass' => esc_html__('Current Password','propertya'),
			'new_pass' => esc_html__('New Password','propertya'),
			'conf_pass' => esc_html__('Confirm Password','propertya'),
			'change_pass_btn' => esc_html__('Change My Password','propertya'),
			'accn_delete' => esc_html__('Account Deletion','propertya'),
			'accn_delete_msg' => esc_html__('If you want to delete your account your all data will be removed from this site.','propertya'),
			'accn_delete_btn' => esc_html__('Delete My Account','propertya'),
			'skype' => esc_html__('Skype','propertya'),
			'working_hours' => esc_html__('Working Hours','propertya'),
			'home' => esc_html__('Home','propertya'),
			'page' => esc_html__('Page','propertya'),
			'off' => esc_html__('of','propertya'),
			'user_type' => esc_html__('User Type','propertya'),
			'all_fields_error' 	=>   esc_html__('All fields are required.','propertya'),
			'logout' 	=>   esc_html__('Logout','propertya'),
			'signup' 	=>   esc_html__('Sign Up','propertya'),
			'log' 	=>   esc_html__('Sign In','propertya'),
			'or_reg' 	=>   esc_html__('Or Register With','propertya'),
			'or_log' 	=>   esc_html__('Or Login With','propertya'),
			'processing' 	=>   esc_html__('Processing...','propertya'),
			'google' 	=>   esc_html__('Google','propertya'),
			'fb' 	=>   esc_html__('Facebook','propertya'),
			'details' 	=>   esc_html__('details','propertya'),
			'price' 	=>   esc_html__('Price','propertya'),
			'status' 	=>   esc_html__('Property Status','propertya'),
			'prop_id' 	=>   esc_html__('Property ID','propertya'),
			'prop_size' 	=>   esc_html__('Property Size','propertya'),
			'prop_additional' 	=>   esc_html__('Additional details','propertya'),
			'review_title' 	=>   esc_html__('Review Title','propertya'),
			'your_review' 	=>   esc_html__('Your Review','propertya'),
			'review_write' 	=>   esc_html__('Write a Review','propertya'),
			'rating' 	=>   esc_html__('Rating','propertya'),
			'beds' 	=>   esc_html__('Beds','propertya'),
			'baths' 	=>   esc_html__('Baths','propertya'),
			'size' 	=>   esc_html__('Size','propertya'),
			'fav' 	=>   esc_html__('Favourite','propertya'),
			'favorites' 	=>   esc_html__('Favorites','propertya'),
			'fav_prop' 	=>   esc_html__('Favorites Properties','propertya'),
			'compare' 	=>   esc_html__('Compare','propertya'),
			'member_since' 	=>   esc_html__('Member Since','propertya'),
			'featured_listings' 	=>   esc_html__('Featured Listings ','propertya'),
			'display_name' 	=>   esc_html__('Display Name','propertya'),
			'displayname_popover' 	=>   esc_html__('Agency Agent or Buyer display name','propertya'),
			'get_directions' 	=>   esc_html__('Get Directions','propertya'),
			'working_hours' 	=>   esc_html__('Working Hours','propertya'),
			'prop_id' 	=>   esc_html__('Property ID','propertya'),
			'near_me' 	=>   esc_html__('Near Me','propertya'),
			'verified_listing' 	=>   esc_html__('Verified Listing','propertya'),
			'total_published' 	=>   esc_html__('Total Published','propertya'),
			'total_pending' 	=>   esc_html__('Total Pending','propertya'),
			'total_featured' 	=>   esc_html__('Total Featured','propertya'),
			'total_expired' 	=>   esc_html__('Total Expired','propertya'),
			'total_views' 	=>   esc_html__('Views','propertya'),
			'reviews' 	=>   esc_html__('Property Reviews','propertya'),
			'profile_reviews' 	=>   esc_html__('Profile Reviews','propertya'),
			'submitted' 	=>   esc_html__('Submitted Reviews','propertya'),
			'received' 	=>   esc_html__('Received Reviews','propertya'),
			'invoices' 	=>   esc_html__('Invoices','propertya'),
			'invoice_status' 	=>   esc_html__('Status','propertya'),
			'invoice_transaction' 	=>   esc_html__('Transaction ID','propertya'),
			'invoice_total' 	=>   esc_html__('Total','propertya'),
			'invoice_prop_id' 	=>   esc_html__('Property ID','propertya'),
			'invoice_order_history' 	=>   esc_html__('Orders History','propertya'),
			'invoice_method' 	=>   esc_html__('Method','propertya'),
			'total_avg' 	=>   esc_html__('Total Average','propertya'),
			'total_reviews' 	=>   esc_html__('Total Reviews','propertya'),
			'total_stars' 	=>   esc_html__('Total Stars','propertya'),
			'recommendations' 	=>   esc_html__('Recommendations','propertya'),
			'welcome' 	=>   esc_html__('Welcome back,','propertya'),
			'dashboard' 	=>   esc_html__('Dashboard','propertya'),
			'recent_act' 	=>   esc_html__('Recent Activities','propertya'),
	   );
	   return $localization;
    }
}
add_action( 'after_theme_setup', 'propertya_localization' );

// Theme Error Messages
if( !function_exists('propertya_localization_msgs') )
{
    function propertya_localization_msgs()
	{
		global $messages;
        $messages = array
	    (
			'name_error' => esc_html__('Name field is required.','propertya'),
	   		'mob_error' => esc_html__('Please enter a valid mobile number.','propertya'),
			'email_error' 	=> esc_html__('You have not given a correct e-mail address.','propertya'),
			'whatsapp_error' 	=> esc_html__('Please enter a WhatsApp number.','propertya'),
			'office_no_error' 	=> esc_html__('Please enter a office number.','propertya'),
			'fax_error' 	=> esc_html__('Fax number is required.','propertya'),
			'license_error' 	=> esc_html__('License is required.','propertya'),
			'tax_error' 	=> esc_html__('Tax number is required.','propertya'),
			'web_url_error' 	=> esc_html__('Please enter a valid Website URL.','propertya'),
			'loc_error' 	=>   esc_html__('Location is required.','propertya'),
			'about_error' 	=>   esc_html__('About field is required.','propertya'),
			'fb_error' 	=>   esc_html__('Please enter a valid Facebook URL.','propertya'),
			'tw_error' 	=>   esc_html__('Please enter a valid Twitter URL.','propertya'),
			'ln_error' 	=>   esc_html__('Please enter a valid LinkedIn URL.','propertya'),
			'insta_error' 	=>   esc_html__('Please enter a valid Instagram URL.','propertya'),
			'you_error' 	=>   esc_html__('Please enter a valid Youtube URL.','propertya'),
			'pin_error' 	=>   esc_html__('Please enter a valid Pinterest URL.','propertya'),
			'addr_error' 	=>   esc_html__('Address field is required.','propertya'),
			'all_fields_error' 	=>   esc_html__('All fields are required.','propertya'),
			'type_error' 	=>   esc_html__('Type fields is required.','propertya'),
			'working_hours' 	=>   esc_html__('The working hours field is required.','propertya'),
			'skype' 	=>   esc_html__('The skype field is required.','propertya'),
			'position' 	=>   esc_html__('The position field is required.','propertya'),
			//You have not answered all required fields
	   );
	   return $messages;
    }
}
add_action( 'after_theme_setup', 'propertya_localization_msgs' );